spring : 
    datasource :
        url : jdbc:postgresql://localhost:5432/peche-store
        username : postgres
        password : Chouich0012
        driver-class-name : org.postgresql.Driver
    jpa : 
        hibernate :
            ddl-auto : update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

